-- Supabase: cadastro de técnicos com endereço e CNPJ opcional.
-- Execute no SQL Editor do projeto Supabase.

create table if not exists public.tecnicos (
  id bigint generated by default as identity primary key,
  nome text not null default '',
  telefone text default '',
  cnpj text default '',
  endereco text not null default '',
  numero text default '',
  bairro text default '',
  cidade text default '',
  uf text default '',
  cep text default '',
  latitude double precision,
  longitude double precision,
  equipamentos text default '',
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Chave única por nome+telefone para upsert (mesmo critério do D1).
create unique index if not exists tecnicos_nome_telefone_uidx
  on public.tecnicos (nome, telefone);

-- Evita duplicidade simples por CNPJ quando informado.
create unique index if not exists tecnicos_cnpj_uidx
  on public.tecnicos (cnpj)
  where cnpj <> '';

-- Índice para listar técnicos ativos em ordem alfabética.
create index if not exists tecnicos_ativo_nome_idx
  on public.tecnicos (ativo, nome);

-- RLS: permite leitura/inserção anônima para a anon key do front.
alter table public.tecnicos enable row level security;

drop policy if exists "anon read tecnicos" on public.tecnicos;
create policy "anon read tecnicos"
  on public.tecnicos
  for select
  using (true);

drop policy if exists "anon insert tecnicos" on public.tecnicos;
create policy "anon insert tecnicos"
  on public.tecnicos
  for insert
  with check (true);

drop policy if exists "anon update tecnicos" on public.tecnicos;
create policy "anon update tecnicos"
  on public.tecnicos
  for update
  using (true)
  with check (true);

drop policy if exists "anon delete tecnicos" on public.tecnicos;
create policy "anon delete tecnicos"
  on public.tecnicos
  for delete
  using (true);