/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnicosRouteImport } from './routes/tecnicos'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SolicitacoesRouteImport } from './routes/solicitacoes'
import { Route as SapRouteImport } from './routes/sap'
import { Route as RoteirizacaoRouteImport } from './routes/roteirizacao'
import { Route as DistribuicaoRouteImport } from './routes/distribuicao'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ContatosIniciaisRouteImport } from './routes/contatos-iniciais'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as IndexRouteImport } from './routes/index'

const TecnicosRoute = TecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesRoute = SolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SapRoute = SapRouteImport.update({
  id: '/sap',
  path: '/sap',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirizacaoRoute = RoteirizacaoRouteImport.update({
  id: '/roteirizacao',
  path: '/roteirizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuicaoRoute = DistribuicaoRouteImport.update({
  id: '/distribuicao',
  path: '/distribuicao',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosIniciaisRoute = ContatosIniciaisRouteImport.update({
  id: '/contatos-iniciais',
  path: '/contatos-iniciais',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/atendimentos': typeof AtendimentosRoute
  '/chamados': typeof ChamadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos-iniciais': typeof ContatosIniciaisRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/distribuicao': typeof DistribuicaoRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/sap': typeof SapRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/tarefas': typeof TarefasRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/atendimentos': typeof AtendimentosRoute
  '/chamados': typeof ChamadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos-iniciais': typeof ContatosIniciaisRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/distribuicao': typeof DistribuicaoRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/sap': typeof SapRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/tarefas': typeof TarefasRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/atendimentos': typeof AtendimentosRoute
  '/chamados': typeof ChamadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos-iniciais': typeof ContatosIniciaisRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/distribuicao': typeof DistribuicaoRoute
  '/roteirizacao': typeof RoteirizacaoRoute
  '/sap': typeof SapRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/tarefas': typeof TarefasRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamentos'
    | '/atendimentos'
    | '/chamados'
    | '/configuracoes'
    | '/contatos-iniciais'
    | '/diagnostico'
    | '/distribuicao'
    | '/roteirizacao'
    | '/sap'
    | '/solicitacoes'
    | '/tarefas'
    | '/tecnicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/atendimentos'
    | '/chamados'
    | '/configuracoes'
    | '/contatos-iniciais'
    | '/diagnostico'
    | '/distribuicao'
    | '/roteirizacao'
    | '/sap'
    | '/solicitacoes'
    | '/tarefas'
    | '/tecnicos'
  id:
    | '__root__'
    | '/'
    | '/agendamentos'
    | '/atendimentos'
    | '/chamados'
    | '/configuracoes'
    | '/contatos-iniciais'
    | '/diagnostico'
    | '/distribuicao'
    | '/roteirizacao'
    | '/sap'
    | '/solicitacoes'
    | '/tarefas'
    | '/tecnicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentosRoute: typeof AgendamentosRoute
  AtendimentosRoute: typeof AtendimentosRoute
  ChamadosRoute: typeof ChamadosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatosIniciaisRoute: typeof ContatosIniciaisRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DistribuicaoRoute: typeof DistribuicaoRoute
  RoteirizacaoRoute: typeof RoteirizacaoRoute
  SapRoute: typeof SapRoute
  SolicitacoesRoute: typeof SolicitacoesRoute
  TarefasRoute: typeof TarefasRoute
  TecnicosRoute: typeof TecnicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnicos': {
      id: '/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof TecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacoes': {
      id: '/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof SolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sap': {
      id: '/sap'
      path: '/sap'
      fullPath: '/sap'
      preLoaderRoute: typeof SapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteirizacao': {
      id: '/roteirizacao'
      path: '/roteirizacao'
      fullPath: '/roteirizacao'
      preLoaderRoute: typeof RoteirizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuicao': {
      id: '/distribuicao'
      path: '/distribuicao'
      fullPath: '/distribuicao'
      preLoaderRoute: typeof DistribuicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos-iniciais': {
      id: '/contatos-iniciais'
      path: '/contatos-iniciais'
      fullPath: '/contatos-iniciais'
      preLoaderRoute: typeof ContatosIniciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentosRoute: AgendamentosRoute,
  AtendimentosRoute: AtendimentosRoute,
  ChamadosRoute: ChamadosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatosIniciaisRoute: ContatosIniciaisRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DistribuicaoRoute: DistribuicaoRoute,
  RoteirizacaoRoute: RoteirizacaoRoute,
  SapRoute: SapRoute,
  SolicitacoesRoute: SolicitacoesRoute,
  TarefasRoute: TarefasRoute,
  TecnicosRoute: TecnicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
